### ISSUE TITLE
Trip Items

### ISSUE THREAD

**Issue by ShermanA-13** [ShermanA-13/gear-up-be#6]
Create CRUD endpoints for a specific Trip Items

- [x] GET: Items for a Trip  
- [x] POST: Create a Trip Item
- [x] PATCH: Edit Trip Item
- [x] DELETE: Delete a Trip Item
